# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps: [check]
  check:
    - task: test
    - task: lint
    - task: fmt
  fix:
    - cargo clippy --fix -- -D warnings
    - task: fmt
  fmt:
    - cargo fmt
    - git diff
  lint: cargo clippy -- -D warnings
  test: cargo test
